#!/bin/bash

##==## healthcheck.sh - [ System health check and Teams/Slack alert ]

source ./config.sh

mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/$(date +'%Y-%m-%d').log"

log() {
  echo "$(date '+%F %T') | $1" | tee -a "$LOG_FILE"
}

HOSTNAME=$(hostname)
TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S UTC')

# Uptime in minutes
UPTIME_SECONDS=$(( $(date +%s) - $(date -d "$(uptime -s)" +%s) ))
UPTIME_MINUTES=$(( UPTIME_SECONDS / 60 ))

# Metrics
CPU_LOAD=$(awk '{print $1}' /proc/loadavg)
DISK_USE=$(df / | awk 'END{print $5}' | tr -d '%')
ZOMBIES=$(ps -eo stat | grep -c Z)

# Log
log "[*] Starting health check on $HOSTNAME"
log "🕓 Uptime: $UPTIME_MINUTES minutes"
log "🖥️ CPU Load: $CPU_LOAD"
log "💽 Disk Usage on /: $DISK_USE%"
log "🧟 Zombie Processes: $ZOMBIES"

# Top 3 CPU-consuming processes
TOP_PROCS=$(ps -eo pid,comm,%cpu,%mem --sort=-%cpu | head -n 4 | tail -n 3 | \
awk '{printf "| %-5s | %-12s | %-6s | %-8s |\n", $1, $2, $3, $4}')

log "🏃 Top 3 CPU consuming processes:"
log "PID    | Process     | CPU % | MEM %"
echo "$TOP_PROCS" | tee -a "$LOG_FILE"

# Markdown alert message
MARKDOWN_MSG="## ⚠️ sys-health-check Alert — Host: $HOSTNAME

**Timestamp:** $TIMESTAMP

---

### 📊 System Status Overview

| Metric             | Value          | Threshold       | Status     |
|--------------------|----------------|-----------------|------------|
| Uptime             | $UPTIME_MINUTES minutes     | —               | $( [ $UPTIME_MINUTES -lt 60 ] && echo '⚠️ Warning' || echo '✅ OK') |
| CPU Load           | $CPU_LOAD      | $CPU_THRESHOLD  | $( ( $(echo "$CPU_LOAD > $CPU_THRESHOLD" | bc -l) ) && echo '🔥 High' || echo '✅ OK') |
| Disk Usage (/)     | ${DISK_USE}%   | $DISK_THRESHOLD | $( [ $DISK_USE -gt $DISK_THRESHOLD ] && echo '💽 High' || echo '✅ OK') |
| Zombie Processes    | $ZOMBIES       | $ZOMBIE_THRESHOLD | $( [ $ZOMBIES -gt $ZOMBIE_THRESHOLD ] && echo '🧟 High' || echo '✅ OK') |

---

### 🏃 Top Resource-Consuming Processes

| PID   | Process Name | CPU %  | Memory % |
|-------|--------------|--------|----------|
$TOP_PROCS

---

### 🔧 Recommended Actions

- Investigate and optimize resource-heavy processes  
- Free disk space on root (/) partition  
- Review zombie processes and uptime anomalies  

---

*Generated by sys-health-check*"

# Wrap for Teams
TEAMS_MSG="{\"text\": \"$MARKDOWN_MSG\"}"

# Wrap for Slack (supports basic Markdown)
SLACK_MSG="{\"text\": \"$MARKDOWN_MSG\"}"

# Check if thresholds are breached
SEND_ALERT=false
if (( $(echo "$CPU_LOAD > $CPU_THRESHOLD" | bc -l) )) || \
   (( DISK_USE > DISK_THRESHOLD )) || \
   (( ZOMBIES > ZOMBIE_THRESHOLD )) || \
   (( UPTIME_MINUTES < 60 )); then
  SEND_ALERT=true
fi

# Send based on config toggles
if [ "$SEND_ALERT" = true ]; then
  log "⚠️ Threshold exceeded — sending alerts"

  if [ "$SEND_TEAMS" = true ]; then
    curl -s -H "Content-Type: application/json" -d "$TEAMS_MSG" "$TEAMS_WEBHOOK"
    log "📨 Alert sent to Microsoft Teams"
  fi

  if [ "$SEND_SLACK" = true ]; then
    curl -s -H "Content-Type: application/json" -d "$SLACK_MSG" "$SLACK_WEBHOOK"
    log "📨 Alert sent to Slack"
  fi
else
  log "✅ All metrics within thresholds — no alert sent"
fi

log "[✓] Health check complete"